server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://study.rui.ubuntu:3306/docm?characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver