server:
  port: 8090

spring:
  datasource:
    name: aby_docm
    url: jdbc:mysql://study.rui.ubuntu:3306/aby_docm?characterEncoding=utf8&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 16MB

  # thymeleaf
#  thymeleaf:
#    prefix: classpath:/templates/
#    check-template-location: true
#    suffix: .html
#    encoding: UTF-8
#    content-type: text/html
#    cache: false

logging:
  file: ./docm-core.log
  level:
    indi.aby.docm.core.dao: debug
    root: info

docm:
  auth:
    freeUrl: /, /**.ico, /**.json, /static/**, /account/login, /doc
    token:
      priKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDiRlCauEl9cbol10o1iWGRalQ/PpErZXOe+k1Jy034pkarf6yqJI7EKpRtV1XVyfI8hOKe2e1nXw2gP3U9zpiDAYGlJABLr+G7nztcUhQltHYsWHhpSvE7p5aoqfYpCwe2xfwyOKB1K9M97xLTyDJb71IKLP/UVgKc+0hGFBCD9ftH750Y9ggkofqXt7mv/FkcZm8Hz4RicT583ffEwxRMc3nbUNCtv+Tk50RqBFbf7tV7HCWCYIzsEZkNB+LxkPsEuLTVl9RxySMC5ndwlc0V6l7WTftP2z2QHWTg5TIo58q0jTuSLo6rZT754lOCOP/PoSBSRyiXnnHZPy2KYM1fAgMBAAECggEBAMOuU166KLPXekfnW0HZQQtkjN702M5Suh6uD9DVhOSXx13g2A17+AslV58HfC+aqWY09Vay2GAhD8OZnWaKF9KTpu6Np8PMosaC+e7o/Itu+RN4nwlPyjbww5WxBjSQWWdy6Jr15a3u7IwPCJUl+IcQ/D3YlJWonDHuDZ6tE2tJ2hhb38uA9BMitewUwn8nsf20ayJSVtsrGhpHKqzN0hEeRAxqC1+dX2q4IcU94XfPFGL7WW1Tsbkcv9/NKiFGQsOHuj3ENCehYhC/Az7/5BVeoHxEKg7lMlL/ZWSqSxn/4JZjEWgTjR1sZBIbxgixdFOyzVWWYgYW7Hqkinc9oMECgYEA+rdHLu3hRPyxow1X0D1cZmvcvIJMnpn0eYzWt8rxGg3Ugwh8HZCtDt/onPHHajX/ApyAQrLqgAVzIq/P+vgvm0sXCzk/MmIjj7u1xI7zkD9rH58lfFG7YpHeT0EAARXpT/ldwBIy5FsgR0MZGins11COlWBh8I+pds8LKiRcMMkCgYEA5wsqXzYLdZwCuuG4LbnD4Rp+WNuPiiMtjh0+7hNUVycvjdIQBD9qr2P6bJTEsLnVdlFkxyVU2K6LRSU9f5Ymue26LBs5WW4Y6UnSv0jk4Al0G+FVhzMaH1wws21FcF0crUGOTVvvERiGJhmwWCFIr0Hq4TKrRx2LIQLKdRAWiOcCgYEA9HgCUSBjqIE+NV+tYMB0eOp0MtxbGcvFN0C9njmlH2Kc9agwXiPUm8x5ZY/cgxRjtIgmCOOtBWhK/GeyxWV8BlESBz+q/9XyFxVSCHfbx6wPKKZmRvLrZRIXU/BtsKFM/06Iu+EC/uhccSBcOcbnyowifEWfOpLbC56XpGAQBQECgYA2vDhvkfgpBqrG506g1o+HNqWUG3/n8+mI73jHIiEq/IeRi6BrwTJfFspvCteGHqBphWLgowF0y/UGjooBPesyxRUD+fceLq0MJ4cb9gLy6IpvSHTgsMSRhV+sQkjfE9AFY7B4tzztyeeOAyv51PjJPE6Ox1g4YtFhIq4gCY2tJQKBgG8vZrVYxC7KEu/oeKpAqZl8gDH65Q997TPNgM07G3FmWLjEgCWA/AWt/7GgfmfJTUFakOXSrsTSzMu8x+3r6WOzwaQzgpSjdpAsJOhrjx4iMxwRh1hmcPK784/mLAU2i6WQ1mrjOp+NZswskUwBrSGaGKFYXn0JqUtDVbmAqsv0
      expireTime: 1800000
